[package]
name = "shadow-drive-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptohelpers = {version = "^2.0.0", features= ["async", "sha256"]}
futures = "^0.3"
hex = "^0.4"
solana-client = "^1.9"
solana-transaction-status = "^1.9"
solana-account-decoder = "^1.9"
solana-sdk = "^1.9"
spl-associated-token-account = "^1"
spl-token = "^3"
shadow-drive-user-staking = {version = "0.1.1", features = ["no-entrypoint"]}
anchor-lang = "^0.24"
async-trait = "^0.1"
byte-unit = "^4"
lazy_static = "^1"
serde = "^1"
serde_json = "^1"
reqwest = {version = "^0.11", features = ["multipart", "stream"]}
tokio = {version = "1.18.2", features = ["rt", "fs", "io-util"]}
tracing = "^0.1"
