[workspace]
members = [
    "sdk",
    "cli",
    "app",
    "py",
]

[workspace.package]
version = "0.5.0"
authors = [
    "Cavey Cool <caveycool@gmail.com>",
    "Tracy <tracy@tracycodes.com>"
]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/GenesysGo/shadow-drive-rust"