pub mod bad_csam;
pub mod claim_stake;
pub mod crank;
pub mod decrease_storage;
pub mod delete_account;
// pub mod delete_file;
// pub mod edit_file;
pub mod increase_storage;
pub mod initialize_account;
pub mod initialize_config;
pub mod make_account_immutable;
// pub mod move_url;
pub mod migrate;
pub mod mutable_fees;
pub mod refresh_stake;
pub mod request_delete_account;
// pub mod request_delete_file;
pub mod redeem_rent;
pub mod store_file;
pub mod unmark_delete_account;
// pub mod unmark_delete_file;
pub mod update_account;
pub mod update_config;
